all: dat2inc.exe datafile.exe

datafile.exe: datafile.c bme_end.c
	gcc -o datafile.exe datafile.c bme_end.c
	strip datafile.exe

dat2inc.exe: dat2inc.c
	gcc -o dat2inc.exe dat2inc.c
	strip dat2inc.exe

